// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYWkcK-9Ecg_xtyki3CWatt_NNbtpzYoo',
    appId: '1:186883979592:web:67bf12344f2d2987045b7d',
    messagingSenderId: '186883979592',
    projectId: 'music-9c05a',
    authDomain: 'music-9c05a.firebaseapp.com',
    storageBucket: 'music-9c05a.appspot.com',
    measurementId: 'G-XVREYP2TDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0UqhmFpcxLX6jD_gwaykuudk7zXFD3_M',
    appId: '1:186883979592:android:24aebbadb772bc6e045b7d',
    messagingSenderId: '186883979592',
    projectId: 'music-9c05a',
    storageBucket: 'music-9c05a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvX47huLSDSm1ch7zxaOHXTkfSpO8ayXo',
    appId: '1:186883979592:ios:2f27dc51a4e30891045b7d',
    messagingSenderId: '186883979592',
    projectId: 'music-9c05a',
    storageBucket: 'music-9c05a.appspot.com',
    iosBundleId: 'com.example.audioPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvX47huLSDSm1ch7zxaOHXTkfSpO8ayXo',
    appId: '1:186883979592:ios:2f27dc51a4e30891045b7d',
    messagingSenderId: '186883979592',
    projectId: 'music-9c05a',
    storageBucket: 'music-9c05a.appspot.com',
    iosBundleId: 'com.example.audioPlayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYWkcK-9Ecg_xtyki3CWatt_NNbtpzYoo',
    appId: '1:186883979592:web:1961d052d106bcff045b7d',
    messagingSenderId: '186883979592',
    projectId: 'music-9c05a',
    authDomain: 'music-9c05a.firebaseapp.com',
    storageBucket: 'music-9c05a.appspot.com',
    measurementId: 'G-6WFEBKKJ0R',
  );

}